<a href="https://colab.research.google.com/github/deepakantony/colaboratory/blob/master/60_min_blitz_part2_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [14]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [15]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [16]:
print(y.grad_fn) # y was created as a result of an operation, so it has a grad_fn

In [17]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [18]:
# Gradients
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [19]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [20]:
x = torch.randn(3, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
  y = y * 2
print(y)

tensor([ 293.3099, -452.9539, 1155.2230], grad_fn=<MulBackward0>)


In [22]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [24]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
  print((x**2).requires_grad)

True
True
False
