<a href="https://colab.research.google.com/github/deepakantony/colaboratory/blob/master/60min_blitz_what_is_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[1.2286e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [4]:
x = torch.rand(4, 4)
print(x)

tensor([[0.2013, 0.3602, 0.7916, 0.4257],
        [0.2610, 0.4289, 0.1410, 0.0622],
        [0.5626, 0.6453, 0.2108, 0.5234],
        [0.8219, 0.7828, 0.1251, 0.8728]])


In [5]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([[10, 10, 3],[3,4,3]])
print(x)

tensor([[10, 10,  3],
        [ 3,  4,  3]])


In [7]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
y = torch.randn_like(x,dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0458,  1.1692, -0.9716],
        [-1.0330,  1.6976,  1.2176],
        [ 1.8231,  2.9259, -0.4885],
        [ 0.5237, -1.0424,  0.0122],
        [-1.7304, -0.1670, -0.5299]])


In [8]:
print(y.size())
y=y.type(torch.double)
print(y)

torch.Size([5, 3])
tensor([[-1.0458,  1.1692, -0.9716],
        [-1.0330,  1.6976,  1.2176],
        [ 1.8231,  2.9259, -0.4885],
        [ 0.5237, -1.0424,  0.0122],
        [-1.7304, -0.1670, -0.5299]], dtype=torch.float64)


In [9]:
print(x+y)

tensor([[-0.0458,  2.1692,  0.0284],
        [-0.0330,  2.6976,  2.2176],
        [ 2.8231,  3.9259,  0.5115],
        [ 1.5237, -0.0424,  1.0122],
        [-0.7304,  0.8330,  0.4701]], dtype=torch.float64)


In [10]:
print(x.add(y))

tensor([[-0.0458,  2.1692,  0.0284],
        [-0.0330,  2.6976,  2.2176],
        [ 2.8231,  3.9259,  0.5115],
        [ 1.5237, -0.0424,  1.0122],
        [-0.7304,  0.8330,  0.4701]], dtype=torch.float64)


In [11]:
print(torch.add(x,y))

tensor([[-0.0458,  2.1692,  0.0284],
        [-0.0330,  2.6976,  2.2176],
        [ 2.8231,  3.9259,  0.5115],
        [ 1.5237, -0.0424,  1.0122],
        [-0.7304,  0.8330,  0.4701]], dtype=torch.float64)


In [12]:
print(y)
y.add(x)
print(y)
y.add_(x)
print(y)

tensor([[-1.0458,  1.1692, -0.9716],
        [-1.0330,  1.6976,  1.2176],
        [ 1.8231,  2.9259, -0.4885],
        [ 0.5237, -1.0424,  0.0122],
        [-1.7304, -0.1670, -0.5299]], dtype=torch.float64)
tensor([[-1.0458,  1.1692, -0.9716],
        [-1.0330,  1.6976,  1.2176],
        [ 1.8231,  2.9259, -0.4885],
        [ 0.5237, -1.0424,  0.0122],
        [-1.7304, -0.1670, -0.5299]], dtype=torch.float64)
tensor([[-0.0458,  2.1692,  0.0284],
        [-0.0330,  2.6976,  2.2176],
        [ 2.8231,  3.9259,  0.5115],
        [ 1.5237, -0.0424,  1.0122],
        [-0.7304,  0.8330,  0.4701]], dtype=torch.float64)


In [13]:
print(x.t())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [14]:
y[:,2]

tensor([0.0284, 2.2176, 0.5115, 1.0122, 0.4701], dtype=torch.float64)

In [15]:
x.add_(y)

tensor([[0.9542, 3.1692, 1.0284],
        [0.9670, 3.6976, 3.2176],
        [3.8231, 4.9259, 1.5115],
        [2.5237, 0.9576, 2.0122],
        [0.2696, 1.8330, 1.4701]], dtype=torch.float64)

In [16]:
print(x)


tensor([[0.9542, 3.1692, 1.0284],
        [0.9670, 3.6976, 3.2176],
        [3.8231, 4.9259, 1.5115],
        [2.5237, 0.9576, 2.0122],
        [0.2696, 1.8330, 1.4701]], dtype=torch.float64)


In [17]:
x[:,:]

tensor([[0.9542, 3.1692, 1.0284],
        [0.9670, 3.6976, 3.2176],
        [3.8231, 4.9259, 1.5115],
        [2.5237, 0.9576, 2.0122],
        [0.2696, 1.8330, 1.4701]], dtype=torch.float64)

In [18]:
x[:,-1]

tensor([1.0284, 3.2176, 1.5115, 2.0122, 1.4701], dtype=torch.float64)

In [19]:
x[:,-1][1:3]

tensor([3.2176, 1.5115], dtype=torch.float64)

In [20]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x,"\n",y,"\n",z)

tensor([[0.4197, 0.3031, 0.7732, 0.6365],
        [0.6010, 0.0260, 0.3372, 0.7509],
        [0.8545, 0.7895, 0.6350, 0.4174],
        [0.1330, 0.3036, 0.6739, 0.1841]]) 
 tensor([0.4197, 0.3031, 0.7732, 0.6365, 0.6010, 0.0260, 0.3372, 0.7509, 0.8545,
        0.7895, 0.6350, 0.4174, 0.1330, 0.3036, 0.6739, 0.1841]) 
 tensor([[0.4197, 0.3031, 0.7732, 0.6365, 0.6010, 0.0260, 0.3372, 0.7509],
        [0.8545, 0.7895, 0.6350, 0.4174, 0.1330, 0.3036, 0.6739, 0.1841]])


In [21]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.3989])
0.3989484906196594


In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [24]:
a.add_(2)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a,1,out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
if torch.cuda.is_available():
    print("How? Hmm, I have CUDA in this machine!")
else:
    print("Thats what I thought! No CUDA on this machine!")

Thats what I thought! No CUDA on this machine!
